export const STORAGE_KEY = "dialer-demo-v2";
export const CHANNEL_NAME = "dialer-demo";

export const IVR_PHASES = {
  idle: "idle",
  incoming: "incoming",
  gather: "gather",
  ringing: "ringing",
  holding: "holding",
  ended: "ended",
};

export const CALL_PHASES = {
  idle: "idle",
  connecting: "connecting",
  ringing: "ringing",
  in_progress: "in_progress",
  ended: "ended",
};

export const CALL_STATUS_LABELS = {
  queued: "Queued",
  ringing: "Ringing",
  "in-progress": "In progress",
  completed: "Completed",
  "no-answer": "No answer",
  busy: "Busy",
  failed: "Failed",
};

function ago(minutes) {
  return Date.now() - minutes * 60 * 1000;
}

export function createSeedState() {
  const now = Date.now();
  return {
    company: {
      name: "Dialer",
      tagline: "Outbound dialer · inbound IVR · leads · team chat",
    },
    currentUserId: "u-agent",
    users: [
      {
        id: "u-agent",
        username: "alex",
        displayName: "Alex Rivera",
        role: "agent",
        presence: "online",
        shift: "day",
      },
      {
        id: "u-sup",
        username: "sam",
        displayName: "Sam Chen",
        role: "supervisor",
        presence: "online",
        shift: "day",
      },
      {
        id: "u-mgr",
        username: "morgan",
        displayName: "Morgan Lee",
        role: "manager",
        presence: "away",
        shift: "day",
      },
      {
        id: "u-proc",
        username: "priya",
        displayName: "Priya Shah",
        role: "processor",
        presence: "online",
        shift: "day",
      },
      {
        id: "u-admin",
        username: "admin",
        displayName: "Jordan Admin",
        role: "admin",
        presence: "online",
        shift: "day",
      },
    ],
    activeCall: null,
    callLogs: [
      {
        id: "c-1003",
        toNumber: "4155550198",
        phoneLabel: "415-555-0198",
        customerName: "Jamie Ortiz",
        status: "completed",
        durationSeconds: 312,
        agentDurationSeconds: 318,
        customerDurationSeconds: 312,
        recording: true,
        conference: false,
        createdAt: ago(18),
        agentId: "u-agent",
      },
      {
        id: "c-1002",
        toNumber: "2125550144",
        phoneLabel: "212-555-0144",
        customerName: "Taylor Brooks",
        status: "no-answer",
        durationSeconds: 0,
        agentDurationSeconds: 42,
        customerDurationSeconds: 0,
        recording: false,
        conference: false,
        createdAt: ago(55),
        agentId: "u-agent",
      },
      {
        id: "c-1001",
        toNumber: "6465550177",
        phoneLabel: "646-555-0177",
        customerName: "Riley Quinn",
        status: "completed",
        durationSeconds: 540,
        agentDurationSeconds: 548,
        customerDurationSeconds: 540,
        recording: true,
        conference: true,
        createdAt: ago(140),
        agentId: "u-sup",
      },
    ],
    leads: [
      {
        id: "l-1",
        name: "Jamie Ortiz",
        phone: "415-555-0198",
        email: "jamie@orbitmail.demo",
        serviceType: "streams",
        phase: "active",
        progressTags: ["verified"],
        contactTags: ["appointment"],
        paymentMethod: "card",
        paymentChargeStatus: null,
        paymentProcessor: null,
        amount: 189,
        assigneeId: "u-agent",
        processorId: "u-proc",
        notes: "Follow up on package upgrade. Prefers afternoon calls.",
        createdAt: ago(60 * 24 * 2),
        updatedAt: ago(20),
      },
      {
        id: "l-2",
        name: "Taylor Brooks",
        phone: "212-555-0144",
        email: "taylor.brooks@demo.net",
        serviceType: "cable",
        phase: "active",
        progressTags: [],
        contactTags: ["voicemail"],
        paymentMethod: null,
        paymentChargeStatus: null,
        paymentProcessor: null,
        amount: 0,
        assigneeId: "u-agent",
        processorId: null,
        notes: "Left voicemail — retry tomorrow morning.",
        createdAt: ago(60 * 24),
        updatedAt: ago(50),
      },
      {
        id: "l-3",
        name: "Riley Quinn",
        phone: "646-555-0177",
        email: "riley.q@demo.io",
        serviceType: "direct",
        phase: "closed",
        progressTags: ["verified", "sale_done", "processed"],
        contactTags: [],
        paymentMethod: "card",
        paymentChargeStatus: "charged",
        paymentProcessor: "auth",
        amount: 249,
        assigneeId: "u-sup",
        processorId: "u-proc",
        notes: "Sale closed. Card charged via Auth.",
        createdAt: ago(60 * 24 * 5),
        updatedAt: ago(130),
      },
      {
        id: "l-4",
        name: "Casey Nguyen",
        phone: "310-555-0162",
        email: "casey.n@demo.co",
        serviceType: "dish",
        phase: "active",
        progressTags: ["verified", "sale_done"],
        contactTags: [],
        paymentMethod: "e_check",
        paymentChargeStatus: null,
        paymentProcessor: null,
        amount: 159,
        assigneeId: "u-agent",
        processorId: "u-proc",
        notes: "Needs processor review before close.",
        createdAt: ago(60 * 12),
        updatedAt: ago(90),
      },
      {
        id: "l-5",
        name: "Avery Kim",
        phone: "718-555-0133",
        email: "avery.kim@demo.org",
        serviceType: "streams",
        phase: "cancelled",
        progressTags: [],
        contactTags: ["hangup"],
        paymentMethod: null,
        paymentChargeStatus: null,
        paymentProcessor: null,
        amount: 0,
        assigneeId: "u-agent",
        processorId: null,
        notes: "Not interested — do not call again.",
        createdAt: ago(60 * 36),
        updatedAt: ago(200),
      },
    ],
    conversations: [
      {
        id: "conv-1",
        title: "Floor chat",
        participantIds: ["u-agent", "u-sup", "u-mgr", "u-proc"],
        unreadFor: {},
      },
      {
        id: "conv-2",
        title: "Alex ↔ Sam",
        participantIds: ["u-agent", "u-sup"],
        unreadFor: { "u-agent": 1 },
      },
    ],
    messages: [
      {
        id: "m-1",
        conversationId: "conv-1",
        senderId: "u-sup",
        body: "Good morning team — focus on appointment callbacks first.",
        createdAt: ago(95),
      },
      {
        id: "m-2",
        conversationId: "conv-1",
        senderId: "u-agent",
        body: "On it. Dialing Jamie Ortiz next.",
        createdAt: ago(90),
      },
      {
        id: "m-3",
        conversationId: "conv-1",
        senderId: "u-proc",
        body: "Casey Nguyen is ready for processing when sale_done lands.",
        createdAt: ago(70),
      },
      {
        id: "m-4",
        conversationId: "conv-2",
        senderId: "u-sup",
        body: "Need a conference on Riley if they call back about billing.",
        createdAt: ago(40),
      },
    ],
    activeConversationId: "conv-1",
    ivrSession: null,
    ivrAlert: null,
    ivrNotifications: [
      {
        id: "ivr-1",
        callSid: "CA_demo_seed_1",
        fromNumber: "415-555-0198",
        toNumber: "+1 (555) 010-2000",
        choice: "1",
        lastEventType: "gather",
        customer: {
          id: "l-1",
          fullName: "Jamie Ortiz",
          phone: "415-555-0198",
        },
        readAt: null,
        createdAt: ago(12),
        updatedAt: ago(11),
      },
      {
        id: "ivr-2",
        callSid: "CA_demo_seed_2",
        fromNumber: "503-555-0188",
        toNumber: "+1 (555) 010-2000",
        choice: "0",
        lastEventType: "incoming",
        customer: null,
        readAt: ago(90),
        createdAt: ago(95),
        updatedAt: ago(94),
      },
    ],
    metrics: {
      callsToday: 14,
      talkMinutes: 86,
      leadsTouched: 9,
      salesClosed: 2,
    },
    nextCallNum: 1004,
    nextLeadNum: 6,
    nextMessageNum: 5,
    nextIvrNum: 3,
    updatedAt: now,
  };
}
